### ISSUE TITLE
XKTEntity has no meshes - Conversion issue

### ISSUE THREAD

**Issue by phxd88** [xeokit/xeokit-xkt-utils#32]
Hi,
I tried convert2xkt.js via command line with a lot of IFC models. 
The conversion process finishes well but for every model (included sample IFC models: e.g. Duplex, MAP...) different entities are not created. Geometries have been validated and checked well. 

Can you help me?
thanks

here is the sample of MAP.ifc conversion:

[convert2xkt] Reading input file: ./assets/models/ifc/MAP.ifc
[convert2xkt] Input file size: 28779.42 kB
[convert2xkt] Converting...
XKTEntity has no meshes - won't create: 3toKckUfH2jBmd$7uhJHa4
XKTEntity has no meshes - won't create: 1T2hYTZj1EsBZaf4hQmaMV
XKTEntity has no meshes - won't create: 0JJqPutQD7fgEmZfa5WIGF
XKTEntity has no meshes - won't create: 0JJqPutQD7fgEmZfa5WIOV
XKTEntity has no meshes - won't create: 0SMh8MeyDD69huEJwvszkI
XKTEntity has no meshes - won't create: 0SMh8MeyDD69huEJwvszht
XKTEntity has no meshes - won't create: 2o1BZCewvA786mTztTsb_9
XKTEntity has no meshes - won't create: 3zXXXEpejFFP0BqpxgfHnh
XKTEntity has no meshes - won't create: 3zXXXEpejFFP0BqpxgfHhD
XKTEntity has no meshes - won't create: 2kL03nWbLAvvTRzX6s02YO
XKTEntity has no meshes - won't create: 2kL03nWbLAvvTRzX6s02Wp
XKTEntity has no meshes - won't create: 2kL03nWbLAvvTRzX6s02bj
XKTEntity has no meshes - won't create: 2kL03nWbLAvvTRzX6s02g7
XKTEntity has no meshes - won't create: 2enSXdsnT8fe5rSym78mcD
XKTEntity has no meshes - won't create: 2enSXdsnT8fe5rSym78mXU
XKTEntity has no meshes - won't create: 2oMUyUT_j0GOP_pjBrdTfL
XKTEntity has no meshes - won't create: 2oMUyUT_j0GOP_pjBrdTlq
XKTEntity has no meshes - won't create: 2YIfhcucz2KOIKFw39XrzG
XKTEntity has no meshes - won't create: 0NUmkRVtDBjAy$Ik8q8A4Z
[convert2xkt] Converted to: XKT v9
[convert2xkt] XKT size: 1424.54 kB
[convert2xkt] Compression ratio: 20.20
[convert2xkt] Conversion time: 48.55 s
[convert2xkt] Converted metaobjects: 2017
[convert2xkt] Converted property sets: 15454
[convert2xkt] Converted drawable objects: 1775
[convert2xkt] Converted geometries: 3680
[convert2xkt] Converted triangles: 169464
[convert2xkt] Converted vertices: 423072
[convert2xkt] Writing XKT file: ./assets/models/xkt/MAP2.ifc.xkt

**Comment by ucalligaro** [comment]
I'm having the same problem. When I run the script to convert from ifc to xkt I get the following log and in the viewer I don't see anything.

[convert2xkt] Reading input file: building.ifc
[convert2xkt] Input file size: 23547.86 kB
[convert2xkt] Converting...
NaN perp!
NaN perp!
NaN in geom!
NaN in geom!
...
NaN in geom!
0 direction in extrude
0 direction in extrude
...
0 direction in extrude
[convert2xkt] Converted to: XKT v9
[convert2xkt] XKT size: 1308.10 kB
[convert2xkt] Compression ratio: 18.00
[convert2xkt] Conversion time: 15.21 s
[convert2xkt] Converted metaobjects: 2084
[convert2xkt] Converted property sets: 2063
[convert2xkt] Converted drawable objects: 2078
[convert2xkt] Converted geometries: 2497
[convert2xkt] Converted triangles: 550200
[convert2xkt] Converted vertices: 1573822
[convert2xkt] Writing XKT file: building.xkt
Converted.

**Comment by saidinusah** [comment]
Hello guys, any fix for this please?

**Comment by xeolabs** [comment]
* xeokit-xkt-utils is now replaced by [xeokit-convert](https://github.com/xeokit/xeokit-convert), which may give better results
* xeokit-xkt-utils and xeokit-convert both use [web-ifc](https://github.com/tomvandig/web-ifc) internally to parse IFC
* web-ifc appears to have a couple of bugs that prevent it from parsing some IFC, resulting in xeokit needing to log the "XKTEntity has no meshes" error
* web-ifc is in alpha, therefore the direct IFC->XKT  conversion option for xeokit-convert is an alpha feature also

@Inusah-Said we provide xeokit-sdk free for use under an open source license, with no obligations for us to expedite fixes or features. However, we can offer a commercial support agreement, if you need better alignment with your enterprise development. Hope that helps. Also, we're always happy to review PRs if provided.
