### ISSUE TITLE
Instanced objects missing in XKT 6

### ISSUE THREAD

**Issue by Francois-Thierry** [xeokit/xeokit-xkt-utils#4]
Hello Lindsay, I hope you are doing well.
I'm super hyped by the new version of the XKT, amazing work !
However I noticed what seems to be a regression..

**Describe the bug**
When trying the new XKT version I noticed that there were some missing elements, both on "jittering" and "correct" version of our demo model.

**To Reproduce**
1. Convert a GLTF model to the latest XKT version
2. Display in xeokit

**Expected behavior**
You can see on the screenshots below that a lot of windows grids and frames are missing. 

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/7921372/98262925-755c6400-1f86-11eb-96db-1d9827489060.png)
After
![image](https://user-images.githubusercontent.com/7921372/98262950-7c837200-1f86-11eb-8ad9-5e333d8b94f9.png)

**Additional context**
Why I think it is more of a regression than a bug is that the model looks correct in your twitter post : https://twitter.com/xeolabs/status/1322179784231866370 but not in the corresponding blog post : http://xeokit.io/blog_full_precision_geometry.html nor in the example.

Thanks in advance for the correction, the full precision emulation is a great feature that will alleviate a lot of troubles for us, especially for the multi-models visualization.

**Comment by xeolabs** [comment]
All fixed @Francois-Thierry , thanks for catching that.

The bug was basically that I forgot to quantize the vertex positions of instanced objects.

The fix is in ````xeokit-xkt-utils````, which is used in ````xeokit-gltf-to-xkt````.

So, to use this fix, enter your ````xeokit-gltf-to-xkt```` directory and ````run npm update @xeokit/xeokit-xkt-utils```` and that should do the trick.

**Comment by xeolabs** [comment]
To test, I re-converted the MAP glTF file to XKT6, and replaced that model in the xeokit-sdk collection. Run that here: https://xeokit.github.io/xeokit-sdk/examples/loading_XKT_jitter_fullPrecision_MAP.html

**Comment by Francois-Thierry** [comment]
It is fixed, thanks a bunch for the swift correction !
